### ISSUE TITLE
/bin/sh: rimraf: not found

### ISSUE THREAD

**Issue by CrossFire10100** [PDNMX/SistemaDeclaraciones_backend#6]
Hola que tal, cuando corro el sistema bajo el ambiente "production"
NODE_ENV=production
No compila correctamente la imagen docker

> root@ip-172-31-26-163:/opt/SistemaDeclaraciones/SistemaDeclaraciones_backend# docker-compose -p declaraciones-backend up -d --build --force-recreate
Building reports
Sending build context to Docker daemon  607.2kB
Step 1/8 : FROM python:3.8
 ---> ea60bde6f16d
Step 2/8 : WORKDIR /code
 ---> Using cache
 ---> 7778c621549a
Step 3/8 : ARG NODE_ENV
 ---> Using cache
 ---> d8b3409d7a3e
Step 4/8 : COPY requirements.txt .
 ---> Using cache
 ---> 244a9621d296
Step 5/8 : RUN pip install -r requirements.txt
 ---> Using cache
 ---> 16df257a34bc
Step 6/8 : COPY . .
 ---> Using cache
 ---> dcd6681eaf66
Step 7/8 : EXPOSE 3001
 ---> Using cache
 ---> 4279de2d8c19
Step 8/8 : CMD [ "python", "./flask_app.py"]
 ---> Using cache
 ---> 9f1d26d841bc
Successfully built 9f1d26d841bc
Successfully tagged declaraciones-backend_reports:latest
Building app
Sending build context to Docker daemon  480.3kB
Step 1/7 : FROM node:14-alpine
 ---> 6f5dba13ae83
Step 2/7 : ADD . /backend
 ---> Using cache
 ---> 88ff3d540900
Step 3/7 : WORKDIR /backend
 ---> Using cache
 ---> 3a8599bebf43
Step 4/7 : ARG NODE_ENV
 ---> Using cache
 ---> 75eec7bb8cfa
Step 5/7 : RUN yarn add global yarn && yarn install && yarn build && yarn cache clean
 ---> Running in 4c367355db6f
yarn add v1.22.17
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning apollo-server-express > subscriptions-transport-ws@0.9.19: The `subscriptions-transport-ws` package is no longer maintained. We recommend you use `graphql-ws` instead. For help migrating Apollo software to `graphql-ws`, see https://www.apollographql.com/docs/apollo-server/data/subscriptions/#switching-from-subscriptions-transport-ws    For general help using `graphql-ws`, see https://github.com/enisdenjo/graphql-ws/blob/master/README.md
warning apollo-server-express > apollo-server-core > subscriptions-transport-ws@0.9.19: The `subscriptions-transport-ws` package is no longer maintained. We recommend you use `graphql-ws` instead. For help migrating Apollo software to `graphql-ws`, see https://www.apollographql.com/docs/apollo-server/data/subscriptions/#switching-from-subscriptions-transport-ws    For general help using `graphql-ws`, see https://github.com/enisdenjo/graphql-ws/blob/master/README.md
warning apollo-server-express > graphql-tools@4.0.8: This package has been deprecated and now it only exports makeExecutableSchema.\nAnd it will no longer receive updates.\nWe recommend you to migrate to scoped packages such as @graphql-tools/schema, @graphql-tools/utils and etc.\nCheck out https://www.graphql-tools.com to learn what package you should use instead
warning apollo-server-express > apollo-server-core > graphql-tools@4.0.8: This package has been deprecated and now it only exports makeExecutableSchema.\nAnd it will no longer receive updates.\nWe recommend you to migrate to scoped packages such as @graphql-tools/schema, @graphql-tools/utils and etc.\nCheck out https://www.graphql-tools.com to learn what package you should use instead
warning apollo-server-express > apollo-server-core > apollo-cache-control@0.14.0: The functionality provided by the `apollo-cache-control` package is built in to `apollo-server-core` starting with Apollo Server 3. See https://www.apollographql.com/docs/apollo-server/migration/#cachecontrol for details.
warning apollo-server-express > apollo-server-core > apollo-tracing@0.15.0: The `apollo-tracing` package is no longer part of Apollo Server 3. See https://www.apollographql.com/docs/apollo-server/migration/#tracing for details
warning apollo-server-express > apollo-server-core > graphql-extensions@0.15.0: The `graphql-extensions` API has been removed from Apollo Server 3. Use the plugin API instead: https://www.apollographql.com/docs/apollo-server/integrations/plugins/
warning apollo-server-express > graphql-tools > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning graphql-auth-directives > graphql-tools@4.0.8: This package has been deprecated and now it only exports makeExecutableSchema.\nAnd it will no longer receive updates.\nWe recommend you to migrate to scoped packages such as @graphql-tools/schema, @graphql-tools/utils and etc.\nCheck out https://www.graphql-tools.com to learn what package you should use instead
warning mongoose > @types/mongodb > @types/bson@4.2.0: This is a stub types definition. bson provides its own type definitions, so you do not need this installed.
warning nyc > istanbul-lib-processinfo > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[3/5] Fetching packages...
[4/5] Linking dependencies...
[5/5] Building fresh packages...
success Saved lockfile.
success Saved 231 new dependencies.
info Direct dependencies
├─ @elastic/elasticsearch@7.12.0
├─ @graphql-tools/load-files@6.3.2
├─ @graphql-tools/merge@6.2.17
├─ @graphql-tools/stitch@7.4.0
├─ @sendgrid/mail@7.4.7
├─ @types/http-errors@1.8.2
├─ apollo-server-express@2.22.2
├─ axios@0.21.4
├─ body-parser@1.19.2
├─ cors@2.8.5
├─ dotenv@8.2.0
├─ express-jwt@6.0.0
├─ express@4.17.3
├─ global@4.4.0
├─ graphql-auth-directives@2.2.2
├─ graphql-compose@7.25.1
├─ graphql-custom-types@1.6.0
├─ graphql-type-json@0.3.2
├─ graphql@15.5.3
├─ http-errors@1.8.1
├─ http-status-codes@2.1.4
├─ jsonwebtoken@8.5.1
├─ localized-strings@0.2.4
├─ md5@2.3.0
├─ mongodb@3.6.12
├─ mongoose-paginate-ts@1.2.6
├─ mongoose@5.12.15
├─ reflect-metadata@0.1.13
└─ yarn@1.22.18
info All dependencies
├─ @apollo/protobufjs@1.2.2
├─ @apollographql/graphql-upload-8-fork@8.1.3
├─ @elastic/elasticsearch@7.12.0
├─ @graphql-tools/batch-delegate@7.0.2
├─ @graphql-tools/batch-execute@7.1.2
├─ @graphql-tools/load-files@6.3.2
├─ @graphql-tools/merge@6.2.17
├─ @graphql-tools/stitch@7.4.0
├─ @graphql-tools/utils@7.10.0
├─ @graphql-tools/wrap@7.0.8
├─ @josephg/resolvable@1.0.1
├─ @nodelib/fs.scandir@2.1.5
├─ @nodelib/fs.stat@2.0.5
├─ @nodelib/fs.walk@1.2.8
├─ @protobufjs/aspromise@1.1.2
├─ @protobufjs/base64@1.1.2
├─ @protobufjs/codegen@2.0.4
├─ @protobufjs/eventemitter@1.1.0
├─ @protobufjs/fetch@1.1.0
├─ @protobufjs/float@1.0.2
├─ @protobufjs/path@1.1.2
├─ @protobufjs/pool@1.1.0
├─ @protobufjs/utf8@1.1.0
├─ @sendgrid/client@7.6.2
├─ @sendgrid/helpers@7.6.2
├─ @sendgrid/mail@7.4.7
├─ @types/accepts@1.3.5
├─ @types/bson@4.2.0
├─ @types/content-disposition@0.5.4
├─ @types/cookies@0.7.7
├─ @types/cors@2.8.8
├─ @types/fs-capacitor@2.0.0
├─ @types/http-assert@1.5.3
├─ @types/http-errors@1.8.2
├─ @types/koa-compose@3.2.5
├─ @types/long@4.0.1
├─ @types/mime@1.3.2
├─ @types/mongodb@3.6.20
├─ @types/webidl-conversions@6.1.1
├─ @types/whatwg-url@8.2.1
├─ @types/ws@7.4.7
├─ @wry/equality@0.1.11
├─ accepts@1.3.8
├─ apollo-cache-control@0.14.0
├─ apollo-datasource@0.9.0
├─ apollo-errors@1.9.0
├─ apollo-graphql@0.9.6
├─ apollo-link@1.2.14
├─ apollo-server-core@2.25.3
├─ apollo-server-errors@2.5.0
├─ apollo-server-express@2.22.2
├─ apollo-tracing@0.15.0
├─ apollo-utilities@1.3.4
├─ array-flatten@1.1.1
├─ assert@1.5.0
├─ async-retry@1.3.3
├─ async@1.5.2
├─ axios@0.21.4
├─ backo2@1.0.2
├─ base64-js@1.5.1
├─ bluebird@3.5.1
├─ body-parser@1.19.2
├─ buffer-equal-constant-time@1.0.1
├─ buffer@5.7.1
├─ busboy@0.3.1
├─ camel-case@4.1.2
├─ charenc@0.0.2
├─ commander@2.20.3
├─ content-disposition@0.5.4
├─ cookie-signature@1.0.6
├─ cookie@0.4.2
├─ core-js-pure@3.21.1
├─ cors@2.8.5
├─ crypt@0.0.2
├─ cssfilter@0.0.10
├─ deepmerge@4.2.2
├─ deprecated-decorator@0.1.6
├─ destroy@1.2.0
├─ dicer@0.3.0
├─ dom-walk@0.1.2
├─ dotenv@8.2.0
├─ ecdsa-sig-formatter@1.0.11
├─ end-of-stream@1.4.4
├─ es-abstract@1.19.4
├─ es-to-primitive@1.2.1
├─ eventemitter3@3.1.2
├─ express-jwt@6.0.0
├─ express-unless@0.3.1
├─ express@4.17.3
├─ extendable-error@0.1.7
├─ fast-glob@3.2.11
├─ fastq@1.13.0
├─ fill-range@7.0.1
├─ finalhandler@1.1.2
├─ follow-redirects@1.14.9
├─ for-each@0.3.3
├─ forwarded@0.2.0
├─ fs-capacitor@2.0.4
├─ get-symbol-description@1.0.0
├─ glob-parent@5.1.2
├─ global@4.4.0
├─ globby@11.0.3
├─ graphql-auth-directives@2.2.2
├─ graphql-compose@7.25.1
├─ graphql-custom-types@1.6.0
├─ graphql-extensions@0.15.0
├─ graphql-subscriptions@1.2.1
├─ graphql-tag@2.12.6
├─ graphql-tools@4.0.8
├─ graphql-type-json@0.3.2
├─ graphql@15.5.3
├─ hpagent@0.1.2
├─ http-errors@1.8.1
├─ http-status-codes@2.1.4
├─ ieee754@1.2.1
├─ internal-slot@1.0.3
├─ ip@1.1.5
├─ ipaddr.js@1.9.1
├─ is-bigint@1.0.4
├─ is-boolean-object@1.1.2
├─ is-buffer@1.1.6
├─ is-callable@1.2.4
├─ is-date-object@1.0.5
├─ is-extglob@2.1.1
├─ is-negative-zero@2.0.2
├─ is-number-object@1.0.7
├─ is-number@7.0.0
├─ is-promise@4.0.0
├─ is-regex@1.1.4
├─ is-shared-array-buffer@1.0.2
├─ is-string@1.0.7
├─ is-symbol@1.0.4
├─ is-weakref@1.0.2
├─ isarray@1.0.0
├─ iterall@1.3.0
├─ jsonwebtoken@8.5.1
├─ jwa@1.4.1
├─ jws@3.2.2
├─ kareem@2.3.2
├─ localized-strings@0.2.4
├─ lodash.includes@4.3.0
├─ lodash.isboolean@3.0.3
├─ lodash.isinteger@4.0.4
├─ lodash.isnumber@3.0.3
├─ lodash.isplainobject@4.0.6
├─ lodash.isstring@4.0.1
├─ lodash.once@4.1.1
├─ lodash.set@4.3.2
├─ lodash.sortby@4.7.0
├─ loglevel@1.8.0
├─ long@4.0.0
├─ lower-case@2.0.2
├─ md5@2.3.0
├─ media-typer@0.3.0
├─ memory-pager@1.5.0
├─ merge-descriptors@1.0.1
├─ merge2@1.4.1
├─ methods@1.1.2
├─ micromatch@4.0.5
├─ mime-db@1.52.0
├─ mime-types@2.1.35
├─ mime@1.6.0
├─ min-document@2.19.0
├─ mongodb-connection-string-url@2.5.2
├─ mongodb@3.6.12
├─ mongoose-legacy-pluralize@1.0.2
├─ mongoose-paginate-ts@1.2.6
├─ mongoose@5.12.15
├─ mpath@0.8.3
├─ mquery@3.2.5
├─ negotiator@0.6.3
├─ no-case@3.0.4
├─ node-fetch@2.6.7
├─ object-assign@4.1.1
├─ object-inspect@1.12.0
├─ object-path@0.11.5
├─ object.assign@4.1.2
├─ object.getownpropertydescriptors@2.1.3
├─ pascal-case@3.1.2
├─ path-to-regexp@0.1.7
├─ path-type@4.0.0
├─ process-nextick-args@2.0.1
├─ process@0.11.10
├─ proxy-addr@2.0.7
├─ punycode@2.1.1
├─ queue-microtask@1.2.3
├─ raw-body@2.4.3
├─ readable-stream@2.3.7
├─ reflect-metadata@0.1.13
├─ regexp-clone@1.0.0
├─ remove-trailing-separator@1.1.0
├─ require-at@1.0.6
├─ retry@0.13.1
├─ reusify@1.0.4
├─ run-parallel@1.2.0
├─ safe-buffer@5.2.1
├─ safer-buffer@2.1.2
├─ saslprep@1.0.3
├─ secure-json-parse@2.4.0
├─ serve-static@1.14.2
├─ sift@13.5.2
├─ smart-buffer@4.2.0
├─ socks@2.6.2
├─ sparse-bitfield@3.0.3
├─ streamsearch@0.1.2
├─ string_decoder@1.1.1
├─ string.prototype.trimend@1.0.4
├─ string.prototype.trimstart@1.0.4
├─ subscriptions-transport-ws@0.9.19
├─ symbol-observable@1.2.0
├─ to-regex-range@5.0.1
├─ tr46@0.0.3
├─ tslib@2.3.1
├─ unbox-primitive@1.0.1
├─ unixify@1.0.0
├─ unpipe@1.0.0
├─ util-deprecate@1.0.2
├─ util.promisify@1.1.1
├─ util@0.10.3
├─ utils-merge@1.0.1
├─ uuid@3.4.0
├─ vary@1.1.2
├─ webidl-conversions@3.0.1
├─ whatwg-url@5.0.0
├─ which-boxed-primitive@1.0.2
├─ ws@7.5.7
├─ xss@1.0.11
├─ yallist@4.0.0
├─ yarn@1.22.18
├─ zen-observable-ts@0.8.21
└─ zen-observable@0.8.15
Done in 32.28s.
yarn install v1.22.17
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.78s.
yarn run v1.22.17
$ rimraf ./build && tsc && copyfiles -u 1 src/**/*.graphql build/ && copyfiles -a -u 1 src/**/*.json build/
/bin/sh: rimraf: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command '/bin/sh -c yarn add global yarn && yarn install && yarn build && yarn cache clean' returned a non-zero code: 127
ERROR: Service 'app' failed to build : Build failed

**Comment by RazielSystems** [comment]
fix this error
